# Generated by Django 3.1.1 on 2020-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
