# Generated by Django 3.1.1 on 2020-09-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200925_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuisine',
        ),
    ]
